### ISSUE TITLE
Add course attributes to schedule generate courses

### ISSUE THREAD

**Issue by bmazerolle** [SENG499-Company-4/Frontend#80]
**Feature description**
Right now when we generate courses, we only accept the course itself as an input. We need to add the ability to handle # of sections on the course and locking the course to specific times/days.

**Proposed solution**
When a course is added to the generate list, add an edit icon to the course, which when clicked opens a dialog. 
This dialog should allow the user to set: 
* The number of sections to be offered for that course 
* ~~An option to lock each section to a given time/days (ie offered on Mon/Thurs from 9:00-10:20am). This would need to be repeated for the the total # of sections offered.~~ (determined to be out of scope from inter company talks on July 4th)
* Add seng to csc ratio (blank by default) to each section

This dialog will also display: 
* The predicted class size for the offering (from algorithm 2)

**Describe alternatives you've considered**
N/A

**Additional context**
Contact @bmazerolle for any questions on the implementation

**Comment by Ahnaf-Ahmed** [comment]
From inter company talks today, it was determined that this page would only allow user to choose amount of sections to be offered and not do course locking
